# secret for mysql password
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop 
    tier: Database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==